---
- name: Converge
  hosts: molecule-ubuntu
  gather_facts: true
  become: true
  tasks:
  - name: Check uname
    ansible.builtin.raw: uname -a
    register: result
    changed_when: false

  - name: Print some info
    ansible.builtin.assert:
      that: result.stdout | regex_search("^Linux")

  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: true
    register: result

  - name: Restart nginx
    ansible.builtin.systemd:
      name: nginx
      state: restarted
    when: result.changed
