{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN set -x && \
    apt update && \
    apt install -y systemd systemd-sysv python3 sudo bash ca-certificates iproute2 python3-apt aptitude rsync && \
    apt remove -y unattended-upgrades
