---
driver:
  name: docker
platforms:
- name: molecule-ubuntu
  image: ubuntu:22.04
  dockerfile: Dockerfile.j2
  privileged: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  command: /sbin/init
