---
driver:
  name: docker
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    hosts:
      nginx:
        hosts:
          molecule-ubuntu:
verifier:
  name: testinfra
platforms:
- name: molecule-ubuntu
  image: ubuntu:22.04
  dockerfile: Dockerfile.j2
  privileged: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  command: /sbin/init
